Repository rarycoringa/sysbanking, pull requests merged in 2024-05, with the labels that each got.

#7 Feature: Initial structure of Django project created
  .gitignore
  Pipfile
  Pipfile.lock
  manage.py
  sysbanking/__init__.py
  sysbanking/asgi.py
  sysbanking/settings.py
  sysbanking/urls.py
  sysbanking/wsgi.py
Labels: feature

#8 Feature: Create accounts implemented
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/migrations/0001_initial.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/templates/accounts/create.html
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  sysbanking/settings.py
  sysbanking/urls.py
Labels: feature

#9 Feature: Retrieve balance implemented
  accounts/mixins.py
  accounts/templates/accounts/base.html
  accounts/templates/accounts/create.html
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/list.html
  accounts/urls.py
  accounts/views.py
Labels: feature

#11 Feature: Deposit functionality implemented
  accounts/models.py
  accounts/templates/accounts/deposit.html
  accounts/templates/accounts/detail.html
  accounts/urls.py
  accounts/views.py
Labels: feature

#12 Feature: User experience improved
  accounts/mixins.py
  accounts/models.py
  accounts/templates/accounts/base.html
  accounts/templates/accounts/create.html
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/list.html
  accounts/urls.py
  accounts/views.py
Labels: feature

#14 Feature: Transfer functionality implemented
  accounts/models.py
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/transfer.html
  accounts/urls.py
  accounts/views.py
Labels: feature

#20 Feature: Work on project README
  README.md
Labels: feature

#21 Bugfix: Accounts shouldn't have negative balance
  accounts/exceptions.py
  accounts/migrations/0002_alter_account_balance_alter_account_number.py
  accounts/models.py
  accounts/templates/accounts/base.html
  accounts/templates/accounts/create.html
  accounts/templates/accounts/deposit.html
  accounts/templates/accounts/transfer.html
  accounts/templates/accounts/withdraw.html
  accounts/views.py
Labels: bugfix

#22 Feature: A new Bonus Account should be implemented
  accounts/migrations/0003_bonusaccount.py
  accounts/mixins.py
  accounts/models.py
  accounts/templates/accounts/create.html
  accounts/templates/accounts/deposit.html
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/list.html
  accounts/templates/accounts/transfer.html
  accounts/templates/accounts/withdraw.html
  accounts/views.py
Labels: feature

#24 Bugfix: Users shouldn't make negative transactions
  accounts/exceptions.py
  accounts/models.py
Labels: bugfix

#28 Feature: Initial balance field for Savings Account
  accounts/templates/accounts/create.html
  accounts/views.py
Labels: feature

#29 Feature: Simple and Bonus Accounts with balance limit equals to -1000
  accounts/models.py
Labels: feature

#32 Hotfix: User should inform initial balance when creating account
  accounts/templates/accounts/create.html
  accounts/views.py
Labels: hotfix

#33 Bugfix: Bonus Accounts should receive 1 point for each $ 150 received via transfer
  accounts/models.py
Labels: bugfix
